### ISSUE TITLE
ChEMBL activity component

### ISSUE THREAD

**Issue by computingfacts** [chembl/GLaDOS#1014]
The Enzyme Portal uses the ChEMBL web compounds for small molecule compounds e.g  [http://wwwdev.ebi.ac.uk/enzymeportal/search/P35913/molecules](http://wwwdev.ebi.ac.uk/enzymeportal/search/P35913/molecules)
![chembl-activity-chart](https://user-images.githubusercontent.com/989800/49733528-ae480d00-fc79-11e8-8b8a-c9eacec7500c.png)

As you can see, the activity chart is not of the same height and hence not aesthetically appealing.
![chembl-activity](https://user-images.githubusercontent.com/989800/49733546-b99b3880-fc79-11e8-9600-2d4d80c89c7d.png)

As per my discussion with David, Please, could you create a separate component that encompasses the associated bioactivities, assays, enzyme etc ? similar to this attached image?
we urgently need this component as our scheduled public release is this week (14/12/2018). Thanks.

**Comment by nclopezo** [comment]
As we discussed earlier, I am changing the deployment process to support some changes required for https://github.com/chembl/GLaDOS/issues/1011. I will try my best to have this ready before Friday.

**Comment by nclopezo** [comment]
This has been implemented for compounds:
http://wwwdev.ebi.ac.uk/chembl/beta/compound_report_card/CHEMBL379596/
and for targets:
http://wwwdev.ebi.ac.uk/chembl/beta/target_report_card/CHEMBL2097163/

Let me know if you need it for other entities.

We are still working on the deployment process because we need to set up other components for a new feature (#1011). Thus, this is deployed in our **wwwdev** server and can be used from there. When we finish refactoring the deployment process it will be in **www**. 

This is the button that generates the link to embed all the section:
<img width="1166" alt="screen shot 2018-12-14 at 11 52 23" src="https://user-images.githubusercontent.com/1944922/50002064-d051d000-ff96-11e8-88d9-47521209ae0f.png">

The layout of the embedded section adapts to the size of the container, you can play with the size by using the embed link and resizing the browser, for example:
http://wwwdev.ebi.ac.uk/chembl/beta/embed/#compound_report_card/CHEMBL379596/activity_charts
http://wwwdev.ebi.ac.uk/chembl/beta/embed/#target_report_card/CHEMBL2097163/activity_charts

**Comment by nclopezo** [comment]
@computingfacts please let me know if this is ok for you.
