### ISSUE TITLE
Visualising protein targets

### ISSUE THREAD

**Issue by Emma-Manners** [chembl/GLaDOS#1055]
Is there a way to visualise and select the isomerases group (or other small groups) from the main image as I can't seem to do this. Is it possible to view multiple sub groups in more detail? The dark text on a dark background is a little tricky to read.

**Comment by Emma-Manners** [comment]
Visualising transferases: Protease and transferase targets are separate groups but when viewing transferases, protease targets were observed within this group (see screenshot).

![Screenshot 2019-03-14 at 12 31 53](https://user-images.githubusercontent.com/46962491/54360995-f5211680-465d-11e9-8587-93a0adea96dd.png)

**Comment by Emma-Manners** [comment]
Visualising enzymes that belong to two categories:

ATPases are often classified as:
1) enzyme/hydrolase **and**
2) transporter/primary active transporter/F-type and V-type ATPases/V-type ATPase. 

These are two separate target categories but the ATPase subcategories are appearing under the hydrolase group instead of solely the transporter group (see attached screenshot).

![Screenshot 2019-03-14 at 13 24 15](https://user-images.githubusercontent.com/46962491/54362085-3ca8a200-4660-11e9-8702-db4592c39933.png)

**Comment by agaulton** [comment]
Issue above is a bug. ATPase classifications should not be displayed under the hydrolase branch. It looks like different branches of the classification are being merged because of the proteins that are linked to them. See for example old interface: 
![Screenshot 2019-05-29 at 12 17 11](https://user-images.githubusercontent.com/7058697/58553177-2399a100-820c-11e9-9dff-d32d8e102445.png)

**Comment by nclopezo** [comment]
This is fixed now:
https://www.ebi.ac.uk/chembl/
