### ISSUE TITLE
UTF8 issues in downloaded csv/tsv files

### ISSUE THREAD

**Issue by datasome** [chembl/GLaDOS#1156]
Although UTF8 characters are shown correctly on https://www.ebi.ac.uk/chembl/g/#search_results/all/query=H%C3%BCttner, they are not correct when downloaded as csv, tsv - in a downloaded file I see e.g. Sˆrgel F, H¸ttner S

**Comment by nclopezo** [comment]
The files are actually encoded with utf-16-le (UTF 16 Little Endian), this is because Microsoft Excel was having troubles with the UTF 8 encoding, the encoding that works the best (at least according to what I investigated, is UTF 16). Other users have also reported this. @agaulton Should we just use UTF 8 encoding?

**Comment by nclopezo** [comment]
After discussion with @agaulton, the files will be UTF8 from now on.

**Comment by nclopezo** [comment]
All download files are UTF-8 now.

**Comment by nclopezo** [comment]
Done in https://github.com/chembl/GLaDOS/pull/1159
