### ISSUE TITLE
Show full Compound Representations on Compound Report Card

### ISSUE THREAD

**Issue by agaulton** [chembl/GLaDOS#250]
Can see the need to abbreviate the InChI here, but I think we should show the full InChI key and smiles (where it's not longer than what we're showing for InChI at least)

**Comment by agaulton** [comment]
Adding screen shot as I just realised this doesn't happen on Firefox, only safari...
![cpdreps](https://user-images.githubusercontent.com/7058697/31441466-22cd1d84-ae8b-11e7-8811-b5957643819c.jpeg)

**Comment by mnowotka** [comment]
Yes, defintely no string shorter than 28 characters should be abbreviated.

**Comment by nclopezo** [comment]
@agaulton, could you please paste here the url for which you have the issue? I have not been able to reproduce it.

**Comment by agaulton** [comment]
e.g., https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL192/

**Comment by nclopezo** [comment]
For the record, it happens in safari 10.5.

**Comment by mnowotka** [comment]
We spent quite a lot of time on this issue and:
 - we couldn't reproduce it on any other environment apart from Safari 10.5 on the latest macbook pro
 - since 10.5 is already outdated it's much easier to update to the latest Safari then invest time to solve this issue
 - I asked Desktop team to provide a latest MacBook pro but they quickly check and they also can't reproduce the problem, for the record I'm attaching a screenshot they sent to me.
<img width="1188" alt="screen shot 2017-11-08 at 10 25 35" src="https://user-images.githubusercontent.com/837119/32580258-56cf81b4-c4dc-11e7-8104-c9d0212c324b.png">
