### ISSUE TITLE
Spelling corrections

### ISSUE THREAD

**Issue by anne123** [chembl/GLaDOS#268]
pChEMBL heading in browse activities table - case is important
This is also wrong in show/hide columns list

Ligand efficiency plots incorrect spelling of efficiency

ChEMMBL ID on cell line report card

**Comment by agaulton** [comment]
Also QUED weighted on bioactivity table - should be QED Weighted

**Comment by mnowotka** [comment]
@nclopezo we should have all the strings in a single file to easy raname when needed. I guess this is related to #267

**Comment by nclopezo** [comment]
We created configuration files for the strings here: https://github.com/chembl/GLaDOS/tree/master/src/glados/locale/en/LC_MESSAGES

You can see all the official strings values in this page:
https://chembl-glados.herokuapp.com/string_standardisation_test/
There is a ghost inspector test that checks takes a screenshot and should notify when it changes: https://app.ghostinspector.com/tests/59ea1bf7639a7d76ba1dc1c1

Not all the labels in that page are currently correct, because Juan generated the values from a script. We will continue using this new system while we set the correct columns for compounds/ targets/ activities etc... We will start to do this from next Monday. 

The spelling errors reported here have been corrected:
```
pChEMBL heading in browse activities table - case is important
This is also wrong in show/hide columns list
```
https://chembl-glados.herokuapp.com/activities/

```
Ligand efficiency plots incorrect spelling of efficiency
```
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL2093868/

```
ChEMMBL ID on cell line report card
```
https://chembl-glados.herokuapp.com/cell_line_report_card/CHEMBL3308583/

```
Also QUED weighted on bioactivity table - should be QED Weighted
```
I guess you meant the compounds table:

https://chembl-glados.herokuapp.com/compounds/

**Comment by anne123** [comment]
Efficiency is still spelt incorrectly on the ligand efficiency plots (both axes)
Otherwise I can't see any other errors.

**Comment by nclopezo** [comment]
The spelling error in the axes has been fixed:
https://chembl-glados.herokuapp.com/target_report_card/CHEMBL2093868/
@mnowotka this should be the last error pending for this to be finished.
