### ISSUE TITLE
Improve report card markup

### ISSUE THREAD

**Issue by mnowotka** [chembl/GLaDOS#299]
In order to be better parsable and undestandable by web crawlers we should enhance report card markup so it's compatible with the following:

 - schema.org
 - twitter
 - facebook
 - slack

I think the last three items use the common markup guidelines.

**Comment by laurajunco** [comment]
https://www.ebi.ac.uk/chembl/beta/

**Comment by nclopezo** [comment]
Thanks @laurajunco! I will keep this open because we know that it is possible to get more data from elasticsearch, but he had to remove that because there is a problem with the tests in travis. But from your side, don't worry.

**Comment by laurajunco** [comment]
This is Done:
For some reason it doesn't work for Skype when using https but I couldn't fix this problem

![screen shot 2018-06-07 at 14 22 01](https://user-images.githubusercontent.com/17466890/41102264-5b904d64-6a5e-11e8-98ba-95f10b9943fc.png)
![screen shot 2018-06-07 at 14 22 39](https://user-images.githubusercontent.com/17466890/41102856-c3018bf6-6a5f-11e8-960d-fcf789fd7165.png)
![screen shot 2018-06-07 at 14 22 50](https://user-images.githubusercontent.com/17466890/41102857-c3253ab0-6a5f-11e8-9272-d5b65c5b1d5e.png)

**Comment by nclopezo** [comment]
This is also very useful for the FAIRness of the interface. Now that we solved the problem that stopped us from finishing this (connection to elasticsearch from heroku, etc) we can add the missing data for:

- [ ] Main page
- [ ] Compounds
- [ ] Targets
- [ ] Assays
- [ ] Documents
- [ ] Tissues
- [ ] Cell Lines

**Comment by nclopezo** [comment]
During the Biohackathon 2018 in Paris, the MolecularEntity was proposed in [Bioschemas](bioschemas.org):
http://bioschemas.org/devTypes/MolecularEntity/
Compound report cards now produce this output, not all properties are currently available. And for others some discussion is needed about how to implement it. 
Also, for some types of compounds no metadata is generated because they could be different entities that are also being used or will be proposed in bioschemas (Protein, Enzyme, etc...):
https://github.com/chembl/GLaDOS/blob/master/src/glados/schema_tags_generator.py#L34

**Comment by nclopezo** [comment]
Work on this matter will continue. For now this is replaced by https://github.com/chembl/GLaDOS/issues/299
