### ISSUE TITLE
Histograms in report cards: in huge screens the histogram stops growing with the screen size.

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#613]
When histograms are seen in huge screens, it seems that there is an absolute maximum width that the histogram gets. And then it doesn't fill the container completely.
See for example in https://chembl-glados.herokuapp.com/compound_report_card/CHEMBL25/
![screen shot 2018-02-19 at 11 29 34](https://user-images.githubusercontent.com/1944922/36375923-20f5197c-1569-11e8-82cf-4cbe78bb9bff.png)

**Comment by mnowotka** [comment]
Actually I asked @laurajunco to apply max_height to histogram so it won't get huge and I think this also should be applied to other widgets (and sections) as we discussed. I would say the problem is not with max height but with the width :P It should always fill available space regardles of the height.
