### ISSUE TITLE
Searching by compound name in upper case does not return the correct result

### ISSUE THREAD

**Issue by FionaEBI** [chembl/GLaDOS#686]
For example, if you put approved drug GLYBURIDE into the search bar at the top of the page, then the compound report card is not returned, but instead a whole load of compound report cards that are unrelated to the query. A workaround is to search for "GLYBURIDE" which returns the correct result. 

Thanks, Fiona

**Comment by mnowotka** [comment]
Interstingly, autosuggestion works correctly but results are stange and there is no highlighting on result mini-cards.

**Comment by juanfmx2** [comment]
Yes, this bug was introduced by the change that supports BLAST sequences and it thinks the text GLYBURIDE is a protein sequence and can't find anything. I'm fixing this. Temporarily you can use get relevant results using lower case text 
http://chembl-glados.herokuapp.com/g/#search_results/glyburide

**Comment by mnowotka** [comment]
One trivial solution would be: if BLAST gives nothing maybe this is not a sequence ;)

**Comment by nbosc** [comment]
I don't know how the solution to this bug is going but maybe an easy fix would be to include a check box to explicitly specify if the query is a sequence.
I know you want to keep the interface as simple as possible but sequence is a very singular example of things you might want to search in chembl. Even if my query looks like a peptide, eg: PRAVASTATIN (a drug name), it would puzzle me to get as a result the proteins that contains the corresponding amino acid sequence even if it is true.

**Comment by juanfmx2** [comment]
This is fixed now!

**Comment by nbosc** [comment]
Good but new issues are on coming!
