### ISSUE TITLE
Create a drug indications entity browser. 

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#953]
In the same way we have an [Activities Browser](https://www.ebi.ac.uk/chembl/beta/g/#browse/activities), a [Compounds Browser](https://www.ebi.ac.uk/chembl/beta/g/#browse/compounds), etc. This replaces https://github.com/chembl/GLaDOS/issues/507

**Comment by nclopezo** [comment]
Similarly to https://github.com/chembl/GLaDOS/issues/954
There is now a drug indications browser:
http://wwwdev.ebi.ac.uk/chembl/test3/add-mechanisms-of-action-browser/g/#browse/drug_indications
If you see the indications for [CHEMBL190](http://wwwdev.ebi.ac.uk/chembl/test3/add-mechanisms-of-action-browser/compound_report_card/CHEMBL190/), you will also se a 'see all' button, which will take you to the indications from the report card. 
Also, we need to sort out:

- [ ] columns in the table
- [ ] filters
- [ ] browse activities link?
- [ ] links from visualisations

**Comment by anne123** [comment]
These are my initial thoughts to get the discussion going but am happy for other to overrule me.
**Columns in Table:**
We need to show a chemical structure (probably the parent and hence aggregate on the parent?)
In addition to what you have include EFO term (for Open Targets compatibility?)
Call max phase column "max_phase for indication"
Include first approval date and possibly USAN dates as optional fields
**Filters**
In some ways I think what you need here is a way to do a text search for a specific indication rather than a filter.  Is this possible? My specific use case I am working on for Argentina is what drugs are in development for Dengue fever?  I can do this by a text search on the old interface but I can't see how filters are going to easily enable this at the moment.
**Browse activities link**
Is the question should we have this on this page?  My feeling is yes again the use case would be select some compounds and see what data there is on them.
**Links from visualisations**
As discussed at lunch yesterday keeping it simple seems sensible so something like the drugs circle opening into 3 circles: drugs, drug targets and drug indications which then display the 3 data sets seems a good start to me.

**Comment by nclopezo** [comment]
Hi Anne, 
> These are my initial thoughts to get the discussion going but am happy for other to overrule me.
> **Columns in Table:**
> We need to show a chemical structure (probably the parent and hence aggregate on the parent?)
> In addition to what you have include EFO term (for Open Targets compatibility?)
> Call max phase column "max_phase for indication"
> Include first approval date and possibly USAN dates as optional fields
> **Filters**
> In some ways I think what you need here is a way to do a text search for a specific indication rather than a filter. Is this possible? My specific use case I am working on for Argentina is what drugs are in development for Dengue fever? I can do this by a text search on the old interface but I can't see how filters are going to easily enable this at the moment.

I will ask Juan next week about the possibility of adding this 'text search' filter to the other filters, it could be done for all entities. 
> **Browse activities link**
> Is the question should we have this on this page? My feeling is yes again the use case would be select some compounds and see what data there is on them.
> **Links from visualisations**
> As discussed at lunch yesterday keeping it simple seems sensible so something like the drugs circle opening into 3 circles: drugs, drug targets and drug indications which then display the 3 data sets seems a good start to me.

Can we meet with @juanfmx2 next monday (when Juan is back) and make a list of things to do for this?

**Comment by anne123** [comment]
Thanks David
I do think a generic text search box in addition to filters might be useful for many data views.  I do keep finding I can get so far with the filters but then can't quite get the set reduced to what I want.

Meeting on Monday is fine with me 10am?

**Comment by nclopezo** [comment]
10 am is ok for me

**Comment by nclopezo** [comment]
Table:
- [ ] Parent compound and image
- [ ] pref name
- [ ] molecule type
- [ ] first approval
Table Optional:
- [ ] same as in mechanisms
Filters:
- [ ] mesh heading
- [ ] efo term
- [ ] max phase for indication
- [ ] molecule type
FIlters Optional:
- [ ] same as in mechanisms

**Comment by nclopezo** [comment]
I will keep this open because there are some details that are still pending.

**Comment by nclopezo** [comment]
new details should be represented in new issues
