### ISSUE TITLE
Create a mechanisms of action entity browser.

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#954]
In the same way we have an [Activities Browser](https://www.ebi.ac.uk/chembl/beta/g/#browse/activities), a [Compounds Browser](https://www.ebi.ac.uk/chembl/beta/g/#browse/compounds), etc. This replaces https://github.com/chembl/GLaDOS/issues/507

**Comment by nclopezo** [comment]
There is now a test server for this. I created a 'mechanisms of action browser':
http://wwwdev.ebi.ac.uk/chembl/test3/add-mechanisms-of-action-browser/g/#browse/mechanisms_of_action

When you go to a compound report card, for example [CHEMBL190](http://wwwdev.ebi.ac.uk/chembl/test3/add-mechanisms-of-action-browser/compound_report_card/CHEMBL190/), in Mechanisms of Action you will see a button that says 'Browse All', if you click on that button, you will be directed to the full list of mechanisms of action in a new tab. 

I think we need to define the following:
- [ ]  Which columns, default/optional, will we add to the table? For many of them we will have to add them to the index.
- [ ] Which filters should we add?
- [ ] Should we merge the rows by salt forms?
- [ ] Should we add a 'browse activities' link?
- [ ] From which visualisations will we generate links to this 'browser'?

A similar process will be done for the Drug Indications.
@juanfmx2, @agaulton, @anne123, @apbento

**Comment by anne123** [comment]
As for indications my initial comments:
 **Which columns, default/optional, will we add to the table? For many of them we will have to add them to the index.**
In addition to what you have
We need to display a chemical structure, again aggregate data on the parent?
Include target name rather than ChEMBL ID has it has more meaning.
Include target type, organism and molecule type
possibly first approval date and USAN stem as optional fields?
Should phase be renamed development_phase?
  **Which filters should we add?**
I think you would want to filter on:
molecule type, development phase, target type, organism and target and protein classification L1 -L3 
  **Should we merge the rows by salt forms?**
I think yes but keep rows separate where there are multiple mechanisms for a compound
  **Should we add a 'browse activities' link?**
I think yes - logic as for the indications table
  **From which visualisations will we generate links to this 'browser'?**
See comment under indications

**Comment by nclopezo** [comment]
Add filters for
- [ ] action type
- [ ] molecule type
- [ ] development phase
- [ ] target type
- [ ] target organism
- [ ] protein classification l1-l3
Optional filters
- [ ] ALL the ones in browse drugs, including hidden ones. If there is a technical reason to leave some of them out, leave them.
Table columns:
- [ ] molecule with image. 
- [ ] pref name for compound.
- [ ] organism
- [ ] target type
Optional:
- [ ] synonyms (in drug browser)
- [ ] first approval
- [ ] usan stem
- [ ] usan year
Link to:
- [ ] browse activities
- [ ] browse indications

**Comment by juanfmx2** [comment]
include smiles in the download

**Comment by nclopezo** [comment]
I will keep this open because there are some details that are still pending.

**Comment by nclopezo** [comment]
new details should be represented in new issues
