### ISSUE TITLE
Browse Drugs urls are not generated correctly.

### ISSUE THREAD

**Issue by nclopezo** [chembl/GLaDOS#987]
In 'Browse Drugs', when the user selects a filter, the urls does not change correctly:
It goes from:
https://www.ebi.ac.uk/chembl/beta/g/#browse/drugs
to
https://www.ebi.ac.uk/chembl/beta/g/#browse/drugs/filter/%5Bobject%20Object%5D

**Comment by FionaEBI** [comment]
I have a similar issue: 
Hello, 
When I access the Withdrawn Drugs directly using the URL: 
https://www.ebi.ac.uk/chembl/beta/g/#browse/drugs/filter/withdrawn_flag%3A1%20AND%20max_phase%3A4 then this works fine to give 172 parent drugs, and clicking on the edit query shows the correct query (withdrawn_flag: 1 AND max_phase:4).

However, if I build the query using the edit query string from the Drugs page (withdrawn_flag: 1 AND max_phase:4), then the url is not correctly formatted to give an output that can be copied and pasted to reproduce the query. https://www.ebi.ac.uk/chembl/beta/g/#browse/drugs/filter/%5Bobject%20Object%5D

**Comment by nclopezo** [comment]
@FionaEBI thanks for giving more details. I will fix it when I work on the share button (in around 2 weeks)

**Comment by nclopezo** [comment]
Hi Fiona, 

> @FionaEBI thanks for giving more details. I will fix it when I work on the share button (in around 2 weeks)

I meant 2 months. 

This is fixed now: https://www.ebi.ac.uk/chembl/beta/g/tiny/LSmMY05X0iNQREOYyFBw6w==

**Comment by FionaEBI** [comment]
Hi David, 
Great - thank you!
Fiona

**Comment by FionaEBI** [comment]
Dear David, 
I’ve been checking the browse drugs url in since the new release:

This works - to search for max phase=4 drugs: 
https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/max_phase%3A4 <https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/max_phase:4 AND withdrawn_flag:1>

But to search for withdrawn_flag AND max_phase 4 drugs doesn’t work...
https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/max_phase%3A4%20AND%20withdrawn_flag%3A1 <https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/max_phase:4 AND withdrawn_flag:1>
or 
https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/withdrawn_flag%3A1 <https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/withdrawn_flag:1>
And the filter on the left hand side panel for drugs doesn’t seem to work when searching by withdrawn_flag...

I have a presentation for TransQST next week and it would be good to display the links to the withdrawn drug set in ChEMBL…

Thanks for your help,
Fiona

**Comment by juanfmx2** [comment]
Hi Fiona,

The issue here is that the withdrawn flag is boolean now:
https://www.ebi.ac.uk/chembl/g/#browse/drugs/filter/withdrawn_flag%3Atrue

However, for some reason in the facets it shows [0,1], we will need to investigate.

**Comment by FionaEBI** [comment]
Dear Juan & David, 
Thank you for the update. I appreciate the quick reply!
Fiona
